// <auto-generated />
using MVC_Eticaret.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_Eticaret.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220305114055_AddBrands")]
    partial class AddBrands
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVC_Eticaret.Models.Altkatagoriler", b =>
                {
                    b.Property<int>("AltKatagoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AltKatagori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltKatagori_Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("katagoriId")
                        .HasColumnType("int");

                    b.HasKey("AltKatagoriId");

                    b.ToTable("AltKatagoriler");
                });

            modelBuilder.Entity("MVC_Eticaret.Models.Brands", b =>
                {
                    b.Property<int>("brand_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("brand_Adet")
                        .HasColumnType("int");

                    b.Property<string>("brand_Adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brand_Link")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("brand_Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("MVC_Eticaret.Models.Katagoriler", b =>
                {
                    b.Property<int>("katagoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Katagori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KatagoriLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("katagoriId");

                    b.ToTable("katagoriler");
                });
#pragma warning restore 612, 618
        }
    }
}
